-- MySQL Script generated by MySQL Workbench
-- Mon Jun 21 17:35:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blzoodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blzoodb` ;

-- -----------------------------------------------------
-- Schema blzoodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blzoodb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `blzoodb` ;

-- -----------------------------------------------------
-- Table `blzoodb`.`smjestaj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`smjestaj` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`smjestaj` (
  `smjestaj_id` INT NOT NULL AUTO_INCREMENT,
  `smjestaj_naziv` VARCHAR(45) NULL,
  `smjestaj_opis` VARCHAR(100) NULL,
  `smjestaj_kapacitet` INT NULL,
  `ekosistem_smjestaja` ENUM('vodeni', 'prasuma', 'artik', 'pustinjski') NULL,
  PRIMARY KEY (`smjestaj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blzoodb`.`zivotinja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`zivotinja` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`zivotinja` (
  `zivotinja_id` INT NOT NULL AUTO_INCREMENT,
  `zivotinja_ime` VARCHAR(45) NULL,
  `zivotinja_vrsta` VARCHAR(45) NULL,
  `datum_prijema` DATE NULL,
  `datum_rodjenja` DATE NULL,
  `spol` ENUM('M', 'Z') NOT NULL,
  `smjestaj_id` INT NOT NULL,
  `zdravstveno_stanje` ENUM('zdrava', 'bolesna', 'gravidna', 'preminula') NOT NULL DEFAULT 'zdrava',
  `tip_ishrane` ENUM('biljojed', 'mesojed', 'svastojed') NULL,
  `broj_hranjenja_dnevno` INT NOT NULL,
  `putanja_do_slike` VARCHAR(45) NULL,
  PRIMARY KEY (`zivotinja_id`),
  CONSTRAINT `fk_zivotinja_smjestaj1`
    FOREIGN KEY (`smjestaj_id`)
    REFERENCES `blzoodb`.`smjestaj` (`smjestaj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_zivotinja_smjestaj1_idx` ON `blzoodb`.`zivotinja` (`smjestaj_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`hrana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`hrana` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`hrana` (
  `hrana_id` INT NOT NULL AUTO_INCREMENT,
  `hrana_naziv` VARCHAR(45) NOT NULL,
  `stanje` INT NOT NULL,
  `potrebno_stanje` VARCHAR(45) NULL,
  PRIMARY KEY (`hrana_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `hrana_naziv_UNIQUE` ON `blzoodb`.`hrana` (`hrana_naziv` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`ZIVOTINJA_ISHRANA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`ZIVOTINJA_ISHRANA` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`ZIVOTINJA_ISHRANA` (
  `hrana_id` INT NOT NULL,
  `zivotinja_id` INT NOT NULL,
  `velicina_porcije_u_g` INT NOT NULL,
  `broj_porcija_dnevno` INT NOT NULL,
  PRIMARY KEY (`hrana_id`, `zivotinja_id`),
  CONSTRAINT `fk_ZIVOTINJA_ISHRANA_hrana`
    FOREIGN KEY (`hrana_id`)
    REFERENCES `blzoodb`.`hrana` (`hrana_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZIVOTINJA_ISHRANA_zivotinja1`
    FOREIGN KEY (`zivotinja_id`)
    REFERENCES `blzoodb`.`zivotinja` (`zivotinja_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ZIVOTINJA_ISHRANA_zivotinja1_idx` ON `blzoodb`.`ZIVOTINJA_ISHRANA` (`zivotinja_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`lijek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`lijek` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`lijek` (
  `lijek_id` INT NOT NULL AUTO_INCREMENT,
  `lijek_naziv` VARCHAR(45) NULL,
  `stanje` INT NOT NULL,
  `potrebno_stanje` INT NULL,
  PRIMARY KEY (`lijek_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `lijek_naziv_UNIQUE` ON `blzoodb`.`lijek` (`lijek_naziv` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`ZIVOTINJA_LIJECENJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`ZIVOTINJA_LIJECENJE` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`ZIVOTINJA_LIJECENJE` (
  `lijek_lijek_id` INT NOT NULL,
  `zivotinja_zivotinja_id` INT NOT NULL,
  `doza_u_mg` INT NOT NULL,
  `doziranje` ENUM('jednom dnevno', 'dva puta dnevno', 'tri puta dnevno', 'jednom sedmicno', 'jednom mjesecno', 'jednom godisnje') NULL,
  `datum_propisivanja` DATE NOT NULL,
  `trajanje_lijecenja_u_danima` INT NOT NULL,
  `bolest` VARCHAR(100) NULL,
  PRIMARY KEY (`lijek_lijek_id`, `zivotinja_zivotinja_id`),
  CONSTRAINT `fk_ZIVOTINJA_LIJECENJE_lijek1`
    FOREIGN KEY (`lijek_lijek_id`)
    REFERENCES `blzoodb`.`lijek` (`lijek_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZIVOTINJA_LIJECENJE_zivotinja1`
    FOREIGN KEY (`zivotinja_zivotinja_id`)
    REFERENCES `blzoodb`.`zivotinja` (`zivotinja_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ZIVOTINJA_LIJECENJE_zivotinja1_idx` ON `blzoodb`.`ZIVOTINJA_LIJECENJE` (`zivotinja_zivotinja_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`odjelenje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`odjelenje` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`odjelenje` (
  `odjelenje_id` INT NOT NULL AUTO_INCREMENT,
  `odjeljenje_naziv` VARCHAR(45) NOT NULL,
  `rukovodilac_id` INT NOT NULL,
  PRIMARY KEY (`odjelenje_id`),
  CONSTRAINT `fk_odjelenje_zaposleni1`
    FOREIGN KEY (`rukovodilac_id`)
    REFERENCES `blzoodb`.`zaposleni` (`zaposleni_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_odjelenje_zaposleni1_idx` ON `blzoodb`.`odjelenje` (`rukovodilac_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`zaposleni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`zaposleni` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`zaposleni` (
  `zaposleni_id` INT NOT NULL AUTO_INCREMENT,
  `lozinka` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `nadredjenii_id` INT NOT NULL,
  `odjelenje_id` INT NOT NULL,
  PRIMARY KEY (`zaposleni_id`),
  CONSTRAINT `fk_zaposleni_zaposleni1`
    FOREIGN KEY (`nadredjenii_id`)
    REFERENCES `blzoodb`.`zaposleni` (`zaposleni_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zaposleni_odjelenje1`
    FOREIGN KEY (`odjelenje_id`)
    REFERENCES `blzoodb`.`odjelenje` (`odjelenje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_zaposleni_zaposleni1_idx` ON `blzoodb`.`zaposleni` (`nadredjenii_id` ASC);

CREATE INDEX `fk_zaposleni_odjelenje1_idx` ON `blzoodb`.`zaposleni` (`odjelenje_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`BRINE_SE_O`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`BRINE_SE_O` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`BRINE_SE_O` (
  `zivotinja_id` INT NOT NULL,
  `zaposleni_id` INT NOT NULL,
  PRIMARY KEY (`zivotinja_id`, `zaposleni_id`),
  CONSTRAINT `fk_BRINE_SE_O_zivotinja1`
    FOREIGN KEY (`zivotinja_id`)
    REFERENCES `blzoodb`.`zivotinja` (`zivotinja_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BRINE_SE_O_zaposleni1`
    FOREIGN KEY (`zaposleni_id`)
    REFERENCES `blzoodb`.`zaposleni` (`zaposleni_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_BRINE_SE_O_zaposleni1_idx` ON `blzoodb`.`BRINE_SE_O` (`zaposleni_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`CUVAR_OBAVJEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`CUVAR_OBAVJEST` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`CUVAR_OBAVJEST` (
  `zivotinja_id` INT NOT NULL,
  `cuvar_id` INT NOT NULL,
  `datum_generisanja` DATE NOT NULL,
  `novo_zdravstveno_stanje` ENUM('zdrava', 'bolesna', 'gravidna', 'preminula') NOT NULL,
  PRIMARY KEY (`zivotinja_id`, `cuvar_id`, `datum_generisanja`, `novo_zdravstveno_stanje`),
  CONSTRAINT `fk_table1_zivotinja1`
    FOREIGN KEY (`zivotinja_id`)
    REFERENCES `blzoodb`.`zivotinja` (`zivotinja_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_zaposleni1`
    FOREIGN KEY (`cuvar_id`)
    REFERENCES `blzoodb`.`zaposleni` (`zaposleni_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_table1_zaposleni1_idx` ON `blzoodb`.`CUVAR_OBAVJEST` (`cuvar_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`proizvod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`proizvod` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`proizvod` (
  `proizvod_id` INT NOT NULL,
  `proizvod_velicina` ENUM('XS', 'S', 'M', 'L', 'XL', 'NA') NOT NULL DEFAULT 'NA',
  `proizvod_naziv` VARCHAR(45) NOT NULL,
  `trgovina_id` INT NOT NULL,
  `cijena` DECIMAL(5,2) NOT NULL,
  `stanje` INT NULL,
  `putanja_do_slike` VARCHAR(45) NULL,
  `potrebno_stanje` INT NULL,
  `kategorija_trgovine` VARCHAR(45) NULL,
  PRIMARY KEY (`proizvod_id`, `proizvod_velicina`),
  CONSTRAINT `fk_proizvod_odjelenje1`
    FOREIGN KEY (`trgovina_id`)
    REFERENCES `blzoodb`.`odjelenje` (`odjelenje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proizvod_odjelenje1_idx` ON `blzoodb`.`proizvod` (`trgovina_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`narudzba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`narudzba` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`narudzba` (
  `narudzba_id` INT NOT NULL AUTO_INCREMENT,
  `proizvod_id` INT NOT NULL,
  `proizvod_velicina` ENUM('XS', 'S', 'M', 'L', 'XL', 'NA') NOT NULL,
  `datum_narudzbe` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ukupna_cijena` DECIMAL(5,2) NOT NULL,
  `kolicina` INT NOT NULL DEFAULT 1,
  `email` VARCHAR(45) NULL,
  `status_narudzbe` ENUM('poslato', 'dostavljeno', 'NA') NULL,
  `adresa` VARCHAR(45) NULL,
  `grad` VARCHAR(45) NULL,
  `drzava` VARCHAR(45) NULL,
  `postanski_broj` VARCHAR(45) NULL,
  PRIMARY KEY (`narudzba_id`),
  CONSTRAINT `fk_narudzba_proizvod1`
    FOREIGN KEY (`proizvod_id`)
    REFERENCES `blzoodb`.`proizvod` (`proizvod_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_narudzba_proizvod1_idx` ON `blzoodb`.`narudzba` (`proizvod_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`ZOO_ZALIHE_OBAVJESTI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`ZOO_ZALIHE_OBAVJESTI` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`ZOO_ZALIHE_OBAVJESTI` (
  `rukovodilac_id` INT NOT NULL,
  `proizvod_id` INT NOT NULL,
  `datum_generisanja` DATE NOT NULL,
  PRIMARY KEY (`rukovodilac_id`, `proizvod_id`, `datum_generisanja`),
  CONSTRAINT `fk_ZOO_ZALIHE_OBAVJESTI_odjelenje1`
    FOREIGN KEY (`rukovodilac_id`)
    REFERENCES `blzoodb`.`odjelenje` (`odjelenje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZOO_ZALIHE_OBAVJESTI_proizvod1`
    FOREIGN KEY (`proizvod_id`)
    REFERENCES `blzoodb`.`proizvod` (`proizvod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ZOO_ZALIHE_OBAVJESTI_proizvod1_idx` ON `blzoodb`.`ZOO_ZALIHE_OBAVJESTI` (`proizvod_id` ASC);


-- -----------------------------------------------------
-- Table `blzoodb`.`TRGOVINA_ZALIHE_OBAVJESTI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blzoodb`.`TRGOVINA_ZALIHE_OBAVJESTI` ;

CREATE TABLE IF NOT EXISTS `blzoodb`.`TRGOVINA_ZALIHE_OBAVJESTI` (
  `odjelenje_id` INT NOT NULL,
  `proizvod_id` INT NOT NULL,
  `proizvod_velicina` ENUM('XS', 'S', 'M', 'L', 'XL', 'NA') NOT NULL,
  PRIMARY KEY (`odjelenje_id`, `proizvod_id`, `proizvod_velicina`),
  CONSTRAINT `fk_TRGOVINA_ZALIHE_OBAVJESTI_odjelenje1`
    FOREIGN KEY (`odjelenje_id`)
    REFERENCES `blzoodb`.`odjelenje` (`odjelenje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRGOVINA_ZALIHE_OBAVJESTI_proizvod1`
    FOREIGN KEY (`proizvod_id` , `proizvod_velicina`)
    REFERENCES `blzoodb`.`proizvod` (`proizvod_id` , `proizvod_velicina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TRGOVINA_ZALIHE_OBAVJESTI_proizvod1_idx` ON `blzoodb`.`TRGOVINA_ZALIHE_OBAVJESTI` (`proizvod_id` ASC, `proizvod_velicina` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
