-- MySQL Script generated by MySQL Workbench
-- Sun May 16 07:00:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blzoodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blzoodb` ;

-- -----------------------------------------------------
-- Schema blzoodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blzoodb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `blzoodb` ;
USE `blzoodb` ;

-- -----------------------------------------------------
-- View `blzoodb`.`cuvariinfoview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`cuvariinfoview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `cuvariinfoview` AS select `brine_se_o`.`cuvar_id` AS `cuvar_id`,`zivotinja`.`zivotinja_id` AS `zivotinja_id`,`zivotinja`.`zivotinja_ime` AS `zivotinja_ime`,`zivotinja`.`zivotinja_vrsta` AS `zivotinja_vrsta`,`zivotinja`.`datum_prijema` AS `datum_prijema`,`zivotinja`.`datum_rodjenja` AS `datum_rodjenja`,`zivotinja`.`spol` AS `spol`,`zivotinja`.`smjestaj_id` AS `smjestaj_id`,`zivotinja`.`zdravstveno_stanje` AS `zdravstveno_stanje`,`zivotinja`.`tip_ishrane` AS `tip_ishrane`,`zivotinja`.`broj_hranjenja_dnevno` AS `broj_hranjenja_dnevno`,`zivotinja`.`putanja_do_slike` AS `putanja_do_slike`,concat(`zaposleni`.`ime`,' ',`zaposleni`.`prezime`) AS `cuvar_ime`,`smjestaj`.`smjestaj_naziv` AS `smjestaj_naziv` from (((`brine_se_o` join `zivotinja` on((`zivotinja`.`zivotinja_id` = `brine_se_o`.`zivotinja_id`))) join `zaposleni` on((`brine_se_o`.`cuvar_id` = `zaposleni`.`zaposleni_id`))) join `smjestaj` on((`smjestaj`.`smjestaj_id` = `zivotinja`.`smjestaj_id`))) */;

-- -----------------------------------------------------
-- View `blzoodb`.`cuvariobavjestiview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`cuvariobavjestiview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `cuvariobavjestiview` AS select `cuvar_obavjest`.`cuvar_id` AS `cuvar_id`,`zivotinja`.`zivotinja_id` AS `zivotinjaID`,`zivotinja`.`zivotinja_ime` AS `zivotinjaIme`,`zivotinja`.`zivotinja_vrsta` AS `vrsta`,`cuvar_obavjest`.`novo_zdravstveno_stanje` AS `zdravstveno_stanje`,date_format(`cuvar_obavjest`.`datum_generisanja`,'%Y-%m-%d') AS `datum` from (`cuvar_obavjest` join `zivotinja` on((`cuvar_obavjest`.`zivotinja_id` = `zivotinja`.`zivotinja_id`))) */;

-- -----------------------------------------------------
-- View `blzoodb`.`hranazivotinjeview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`hranazivotinjeview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `hranazivotinjeview` AS select `zivotinja_ishrana`.`zivotinja_id` AS `zivotinja_id`,`zivotinja_ishrana`.`hrana_id` AS `hrana_id`,`zivotinja_ishrana`.`velicina_porcije_u_g` AS `velicina_porcije_u_g`,`zivotinja_ishrana`.`broj_porcija_dnevno` AS `broj_porcija_dnevno`,`hrana`.`hrana_naziv` AS `hrana_naziv`,`hrana`.`stanje` AS `stanje`,`hrana`.`potrebno_stanje` AS `potrebno_stanje`,`zivotinja`.`zivotinja_ime` AS `zivotinje_ime` from ((`zivotinja_ishrana` join `hrana` on((`zivotinja_ishrana`.`hrana_id` = `hrana`.`hrana_id`))) join `zivotinja` on((`zivotinja_ishrana`.`zivotinja_id` = `zivotinja`.`zivotinja_id`))) */;

-- -----------------------------------------------------
-- View `blzoodb`.`trgovinaobavjestiview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`trgovinaobavjestiview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `trgovinaobavjestiview` AS select `trgovina_zalihe_obavjesti`.`rukovodilac_id` AS `rukovodilac_id`,`trgovina_zalihe_obavjesti`.`proizvod_id` AS `proizvod_id`,`trgovina_zalihe_obavjesti`.`proizvod_velicina` AS `proizvod_velicina`,date_format(`trgovina_zalihe_obavjesti`.`datum_generisanja`,'%Y-%m-%d') AS `datum_generisanja`,`proizvod`.`proizvod_naziv` AS `proizvod_naziv` from (`trgovina_zalihe_obavjesti` join `proizvod` on((`trgovina_zalihe_obavjesti`.`proizvod_id` = `proizvod`.`proizvod_id`))) */;

-- -----------------------------------------------------
-- View `blzoodb`.`veterinarlijekoviobavjestiview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`veterinarlijekoviobavjestiview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `veterinarlijekoviobavjestiview` AS select `zoo_zalihe_obavjesti`.`proizvod_id` AS `proizvod_id`,date_format(`zoo_zalihe_obavjesti`.`datum_generisanja`,'%Y-%m-%d') AS `datum_generisanja`,`lijek`.`lijek_naziv` AS `lijekNaziv` from (`zoo_zalihe_obavjesti` join `lijek` on((`zoo_zalihe_obavjesti`.`proizvod_id` = `lijek`.`lijek_id`))) order by date_format(`zoo_zalihe_obavjesti`.`datum_generisanja`,'%Y-%m-%d') */;

-- -----------------------------------------------------
-- View `blzoodb`.`veterinarobavjestiview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`veterinarobavjestiview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `veterinarobavjestiview` AS select `zoo_zalihe_obavjesti`.`proizvod_id` AS `proizvod_id`,date_format(`zoo_zalihe_obavjesti`.`datum_generisanja`,'%Y-%m-%d') AS `datum_generisanja`,`hrana`.`hrana_naziv` AS `hranaNaziv` from (`zoo_zalihe_obavjesti` join `hrana` on((`zoo_zalihe_obavjesti`.`proizvod_id` = `hrana`.`hrana_id`))) order by date_format(`zoo_zalihe_obavjesti`.`datum_generisanja`,'%Y-%m-%d') */;

-- -----------------------------------------------------
-- View `blzoodb`.`zaposlenilistview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`zaposlenilistview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `zaposlenilistview` AS select `zaposleni`.`zaposleni_id` AS `zaposleni_id`,`zaposleni`.`lozinka` AS `lozinka`,`zaposleni`.`ime` AS `ime`,`zaposleni`.`prezime` AS `prezime`,`zaposleni`.`nadredjeni_id` AS `nadredjeni_id`,`zaposleni`.`odjeljenje_id` AS `odjeljenje_id`,`odjeljenje`.`odjeljenje_naziv` AS `odjeljenje_naziv`,concat(`s`.`ime`,' ',`s`.`prezime`) AS `nadredjeni` from ((`zaposleni` join `odjeljenje` on((`odjeljenje`.`odjeljenje_id` = `zaposleni`.`odjeljenje_id`))) join `zaposleni` `s` on((`zaposleni`.`nadredjeni_id` = `s`.`zaposleni_id`))) */;

-- -----------------------------------------------------
-- View `blzoodb`.`zivotinjanalijecenjuview`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `blzoodb`.`zivotinjanalijecenjuview` ;
USE `blzoodb`;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `zivotinjanalijecenjuview` AS select `zivotinja_lijecenje`.`zivotinja_id` AS `zivotinja_id`,`zivotinja_lijecenje`.`lijek_id` AS `lijek_id`,`zivotinja_lijecenje`.`doza_u_mg` AS `doza_u_mg`,`zivotinja_lijecenje`.`doziranje` AS `doziranje`,`zivotinja_lijecenje`.`datum_propisivanja` AS `datum_propisivanja`,`zivotinja_lijecenje`.`trajanje_lijecenja_u_danima` AS `trajanje_lijecenja_u_danima`,`zivotinja_lijecenje`.`bolest` AS `bolest`,date_format((`zivotinja_lijecenje`.`datum_propisivanja` + interval `zivotinja_lijecenje`.`trajanje_lijecenja_u_danima` day),'%M-%d-%Y') AS `uzimatiDo`,`lijek`.`lijek_naziv` AS `lijek_naziv`,`lijek`.`stanje` AS `stanje`,`lijek`.`potrebno_stanje` AS `potrebno_stanje`,`zivotinja`.`zivotinja_ime` AS `zivotinja_ime` from ((`zivotinja_lijecenje` join `lijek` on((`zivotinja_lijecenje`.`lijek_id` = `lijek`.`lijek_id`))) join `zivotinja` on((`zivotinja_lijecenje`.`zivotinja_id` = `zivotinja`.`zivotinja_id`))) where ((`zivotinja_lijecenje`.`datum_propisivanja` + interval `zivotinja_lijecenje`.`trajanje_lijecenja_u_danima` day) >= cast(now() as date)) */;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
